# Results

```{r results= 'asis', echo = FALSE}
MSE_five = as.matrix(c("ols" = ols_mse, "ridge" = ridge_mse, "lasso" = lasso_mse, "pcr" = pc_mse, "plsr" = pls_mse))
colnames(MSE_five) = "MSE"
print(xtable(MSE_five, caption = 'MSE of Five Regression Methods', digits = 5), comment = FALSE)
```

From the MSE table above, we find that all the MSE are very close to each other and the maximum difference between the MSE of ridge and that of lasso. The regression with the smallest MSE is lasso regression, where MSE = `r lasso_mse`. As lasso has the smallest MSE, then we can conlcude that lasso is the best fitted model for the credit data set in this case. Aditionally, the one with the largest MSE is Ridge regression, where MSE is euqual to `r ridge_mse`. this means tha ridge regression provides the worst fitted model for the credit dataset. 

Furthermore, we also include a trendline plot in which the official coefficients are compared.



This trendline plot also allows us to compare how each type of regression models fit a model to the credit data set. We can see from the graph that the lines of PLSR and PCR are very close to each other, and lasso has the least variance with OLS generally. Also, for variables like `Income`, it is almost same in each model, however, for varibles like `Rating` and `Limit`, these estimates vary widely in different regression methods.